### ISSUE TITLE
Make mhpost action consistent with mhget action.

### ISSUE THREAD

**Issue by lzbj** [IBM/openwhisk-data-processing-message-hub#20]
Currently the mhpost.js action is exported as a nodejs module, can we change it like the mhget.js action, and thus remove the package.json file? @krook . Perhaps this is more convenient for deployment for tools like wsk cli or wskdeploy.

**Comment by lzbj** [comment]
sorry, after review the code, seems we'd better put it as a zip file, since openwhisk already support zip actions,  any comments?

**Comment by jzaccone** [comment]
`mhpost.js` depends on an external npm module: `message-hub-rest`, while `mhget.js` has no external dependencies... which is why these are different.

We are already creating the mhpost action using the OpenWhisk support for zipped actions:
```sh
npm install
wsk action create kafka/mhpost-action actions/mhpost/mhpost.zip --kind nodejs:6
```

So I see no change required @lzbj, unless you still see something I don't?

**Comment by lzbj** [comment]
Sure, so you mean we create the zip file when we want the zip file, ok, got it. thank you.
